### ISSUE TITLE
Build failure on aarch64 platform

### ISSUE THREAD

**Issue by xiaofengren** [neo-ai/neo-ai-dlr#1]
I got following build error on my aarch64 platform, may I know whether you try it on aarch64 platform? 

root@aad2441cbcdb5598851a5f655d0a70f7:~/neo-ai-dlr/build# make -j16
[  0%] Building CXX object CMakeFiles/objdlr.dir/src/dlr.cc.o
[  8%] Built target objtreelite_runtime
[ 33%] Built target dmlc
[ 91%] Built target tvm_runtime_static
Scanning dependencies of target treelite_runtime_static
[ 91%] Linking CXX static library ../../../../../3rdparty/neo-ai-treelite/runtime/native/lib/libtreelite_runtime_static.a
[ 91%] Built target treelite_runtime_static
/root/neo-ai-dlr/src/dlr.cc: In member function 'void dlr::DLRModel::SetInput(const char*, const int64_t*, float*, int)':
/root/neo-ai-dlr/src/dlr.cc:248:14: error: 'accumulate' is not a member of 'std'
         std::accumulate(shape, shape + dim, 1, std::multiplies<int64_t>());
              ^~~~~~~~~~
/root/neo-ai-dlr/src/dlr.cc:249:34: error: 'accumulate' is not a member of 'std'
     int64_t expected_size = std::accumulate(
                                  ^~~~~~~~~~
CMakeFiles/objdlr.dir/build.make:62: recipe for target 'CMakeFiles/objdlr.dir/src/dlr.cc.o' failed
make[2]: *** [CMakeFiles/objdlr.dir/src/dlr.cc.o] Error 1
CMakeFiles/Makefile2:107: recipe for target 'CMakeFiles/objdlr.dir/all' failed
make[1]: *** [CMakeFiles/objdlr.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zhiics** [comment]
@xiaofengren Thanks for reporting this. Adding "#include <numeric>" in src/dlc.cc probably could solve the problem.

**Comment by ziyu-guo** [comment]
@xiaofengren thanks for bringing this up, we've been able to build it on A1 instance with AARCH64 Graviton, Ubuntu 16.04 and GNU 5.4.0. We'll add this header for better compatibility with different platforms.

**Comment by xiaofengren** [comment]
@zhiics @ziyu-guo thank you so much for your quick response. After follow your suggestion, I'm able to build successfully. 

root@aad2441cbcdb5598851a5f655d0a70f7:~/neo-ai-dlr/build# make -j16
Scanning dependencies of target objdlr
[ 25%] Built target dmlc
[ 83%] Built target tvm_runtime_static
[ 91%] Built target objtreelite_runtime
[ 91%] Building CXX object CMakeFiles/objdlr.dir/src/dlr.cc.o
[ 91%] Built target treelite_runtime_static
[100%] Built target objdlr
Scanning dependencies of target dlr
[100%] Linking CXX shared library lib/libdlr.so
[100%] Built target dlr
