### ISSUE TITLE
neo-ai-dlr installation error

### ISSUE THREAD

**Issue by rdivyashree1995** [neo-ai/neo-ai-dlr#16]
Python3 error: During installing dlr
Reading https://pypi.python.org/simple/  No local packages or download links found for dlr-1.0-py3.7-linux-x86_64.egg

Python2.7 error: During installing dlr
Reading https://pypi.python.org/simple/  No local packages or download links found for dlr-1.0-py2.7-linux-x86_64.egg

Used  dlr-1.0-py2.7-linux-x86_64.egg available in neo-runtime from AWS console(ML inference on greengrass).

1)What about DLR support for Python 3.5?

2)We ran the pre-compiled model from neo-runtime(Link: https://console.aws.amazon.com/iot/home?region=us-east-1#/software/machine-learning ) dlr for Intel atom(Apollo Lake). We were able to run the inference on Intel core i5 and Intel atom(Bay trial) by changing target device as "cpu" from "opencl"(In both opensource neo-ai-dlr  , But the accuracy was very poor(for all test images labels were same with probability zero).
So, since its optimized for Intel atom Apollo Lake family and not working properly on other platforms? or any other configurations needs to be done from our end?

3)Is DLC fully configured in neo-ai? unable to import tvm and nnvm in sample script(Link: https://github.com/neo-ai/neo-ai-dlr/blob/master/tests/test_dlc_python_test.py ), it throws module not found?
Is there any additional setup needs to be done to perform optimization?

**Comment by ziyu-guo** [comment]
Hi @rdivyashree1995, thanks for bringing your questions to us. Answers below:

1) The Greengrass DLR for Intel Atom is compiled for Deeplens device with Intel Atom and Integrated Graphics, which corresponds to the 'cpu' and 'opencl' target, respectively. The cpu target runs on generic x86 processor, and you should see the same result as TVM runtime on any x86 processor, if the model was compiled for x86 target as well. Can you provide more details on how the models are generated and run?

2)
