### ISSUE TITLE
Where to get complete commands for building locally?

### ISSUE THREAD

**Issue by zubairahmed-ai** [neo-ai/neo-ai-dlr#2]
I'm using it for the first time and I just read [this documentation](https://aws.amazon.com/blogs/aws/amazon-sagemaker-neo-train-your-machine-learning-models-once-run-them-anywhere/) but how can I use this open source code to build for an Kirin or ARM Processor locally on my machine?

**Comment by ziyu-guo** [comment]
Hi @zubairahmed-ai , please follow [this link](https://github.com/neo-ai/neo-ai-dlr/blob/master/DEVELOPMENT.md) to build DLR on arm platforms. Please note that it requires cmake 3.10+, a c++11 compiler and python setuptools package. Thanks and let us know.

**Comment by zubairahmed-ai** [comment]
[CMakeError.log](https://github.com/neo-ai/neo-ai-dlr/files/2815879/CMakeError.log)
[CMakeOutput.log](https://github.com/neo-ai/neo-ai-dlr/files/2815880/CMakeOutput.log)

I am getting the errors below

`
CMake Error at CMakeLists.txt:131 (add_subdirectory):
`
`  The source directory 
   E:/Documents/Projects/neo-ai-dlr/3rdparty/neo-ai-treelite 
   does not contain a CMakeLists.txt file.`

I tried git clone of `neo-ai-treelite` in this but then I still get this error

`
-- Looking for pthread.h
`
`
-- Looking for pthread.h - not found
`
`
-- Found Threads: TRUE
`
`
-- TVM_RUNTIME_LINKER_LIBS:
`
`
-- Configuring incomplete, errors occurred!
`
`
See also "E:/Documents/Projects/neo-ai-dlr/build/CMakeFiles/CMakeOutput.log".
`
`
See also "E:/Documents/Projects/neo-ai-dlr/build/CMakeFiles/CMakeError.log".
`

Not sure how to fix this

**Comment by ziyu-guo** [comment]
Thanks for this find. We're still working on windows build, will keep you updated.

**Comment by zubairahmed-ai** [comment]
> Thanks for this find. We're still working on windows build, will keep you updated.

Thanks for the update, I'm really struggling with this (see my other issues)
Would appreciate a timely update, if you need someone to verify your update, please do let me know

**Comment by knjwhn** [comment]
Hello, the link can't find anymore. is there have any idea to build locally now?@zubairahmed @ziyu-guo

**Comment by ziyu-guo** [comment]
@knjwhn  You can follow [this link](https://github.com/neo-ai/neo-ai-dlr/blob/master/doc/install.rst) to build DLR from source on linux/mac/windows/android now.
