### ISSUE TITLE
Install dlr python package failure

### ISSUE THREAD

**Issue by xiaofengren** [neo-ai/neo-ai-dlr#20]
I had successfully build neo-ai-dlr, when I tried to do installation, I met following error. Can I have your suggestion?

root@aad2441cbcdb5598851a5f655d0a70f7:~/neo-ai-dlr/install/dlr-1.0-py2.py3-cuda90-aarch64# ./install-py2.sh
python is installed
easy_install is installed
pip is installed

Installing numpy...
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/2b/26/07472b0de91851b6656cbc86e2f0d5d3a3128e7580f23295ef58b6862d6c/numpy-1.16.1.zip (5.1MB)
    100% |################################| 5.1MB 128kB/s
Building wheels for collected packages: numpy
  Running setup.py bdist_wheel for numpy ... done
  Stored in directory: /root/.cache/pip/wheels/04/64/e1/283a3672c2865608968594c02a6923311f44d033bcece2683b
Successfully built numpy
Installing collected packages: numpy
  Found existing installation: numpy 1.16.0
    Uninstalling numpy-1.16.0:
      Successfully uninstalled numpy-1.16.0
Successfully installed numpy-1.16.1

Installing dlr for python...
Searching for dlr-1.0-py2.7-linux-aarch64.egg
Reading https://pypi.org/simple/dlr-1.0-py2.7-linux-aarch64.egg/
Couldn't find index page for 'dlr-1.0-py2.7-linux-aarch64.egg' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for dlr-1.0-py2.7-linux-aarch64.egg
error: Could not find suitable distribution for Requirement.parse('dlr-1.0-py2.7-linux-aarch64.egg')
root@aad2441cbcdb5598851a5f655d0a70f7:~/neo-ai-dlr/install/dlr-1.0-py2.py3-cuda90-aarch64#

**Comment by ziyu-guo** [comment]
Hi @xiaofengren It seems you're using installation script that came with Greengrass DLR installer. For neo-ai-dir python installation, please refer to [this doc](https://github.com/neo-ai/neo-ai-dlr/blob/master/doc/install.rst)

`cd python
python3 setup.py install --user`

would be what you need.

**Comment by xiaofengren** [comment]
Thanks a lot for your suggestion.  I'm able to install it successfully.
