### ISSUE TITLE
SageMaker Neo compilation produces different models for different AWS regions

### ISSUE THREAD

**Issue by nwils** [neo-ai/neo-ai-dlr#233]
Hi,

I compiled an object detection model in Frankfurt and Ohio regions. But the compiled model files are different and I could run only the model from the Frankfurt region on my target device. I used the following parameters for model compilation.

target_device = Jetson Nano
Framework = MXNet
input = {"data":[1,3,512,512]}

The compiled models were different. The model from the Frankfurt region has a size of 42.5MB whereas model from the Ohio region is 91.9MB in size. The file details from both regions are attached below.

Frankfurt region
![model_files_frankfurt](https://user-images.githubusercontent.com/65023541/93068370-a7370580-f67c-11ea-8bfa-eaf2c04a33e2.png)

Ohio region
![model_files_ohio](https://user-images.githubusercontent.com/65023541/93068819-40feb280-f67d-11ea-82ab-231ff48b385b.png)

Apart from the _compiled.meta_ file, other files have different sizes. DLR 1.2 version was used to run both models and the files _dlr.h and libdlr.so_ were removed from the compiled models. When I tried to run the compiled model from the Ohio region on Jetson Nano, the following error occurred. 

`ERROR: TVMError: Check failed: f != nullptr: Loader of metadata(runtime.module.loadbinary_metadata) is not presented.#012Stack trace:#012  File "/packages/neo-ai-dlr/3rdparty/tvm/src/runtime/library_module.cc", line 150#012  [bt] (0) /usr/local/dlr/libdlr.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x38) [0x7ef6d17698]#012  [bt] (1) /usr/local/dlr/libdlr.so(tvm::runtime::ProcessModuleBlob(char const*, tvm::runtime::ObjectPtr<tvm::runtime::Library>)+0x2448) [0x7ef72df4a8]#012  [bt] (2) /usr/local/dlr/libdlr.so(tvm::runtime::CreateModuleFromLibrary(tvm::runtime::ObjectPtr<tvm::runtime::Library>)+0x1d0) [0x7ef72e0480]#012  [bt] (3) /usr/local/dlr/libdlr.so(+0x244bb8) [0x7ef6d3fbb8]#012  [bt] (4) /usr/local/dlr/libdlr.so(tvm::runtime::Module::LoadFromFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x1a0) [0x7ef72e5328]#012  [bt] (5) /usr/local/dlr/libdlr.so(dlr::TVMModel::SetupTVMModule(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)+0x1e30) [0x7ef6d70e98]#012  [bt] (6) /usr/local/dlr/libdlr.so(CreateDLRModel+0x1428) [0x7ef6d46a88]`

Why do the compiled models differ based on AWS regions? How can I solve it?
Thanks in advance.

**Comment by trevor-m** [comment]
Hello, we are currently rolling out an update in the Neo service. After the update, you will need DLR 1.3 to run the compiled model. Our updates will go progressively through all regions over a period of a few days which is why you see the difference between regions. Ohio has been updated to DLR 1.3.

**Comment by nwils** [comment]
Thank you.
