### ISSUE TITLE
DLR inference issue on raspberry pi 

### ISSUE THREAD

**Issue by wweic** [neo-ai/neo-ai-dlr#24]
reported by user: https://github.com/aws/sagemaker-python-sdk/issues/593

**Comment by wweic** [comment]
@fast4break We looked at the model you use and think it's because its format might not be supported by Neo(the models were last updated on `2016-10-21`, which means it was generated by a MXNet version at that time). Is it possible for you to try latest Gluon model?

**Comment by fast4break** [comment]
@wweic sure, I will try it asap

**Comment by fast4break** [comment]
@wweic Could not find pretrained Gluon models, so I use the following codes to generate  .params and .json files:
`net = gcv.model_zoo.get_model('resnet50_v1', pretrained=True)
export_block('resnet50_v1', net, preprocess=True, layout='HWC')`
Compress two files into a .tar.gz file and upload to s3, use Sagemaker console to compile the model, failed with following error:
> Client Error: InputConfiguration: Check 1. Input names and shapes matches with trained model. 2. If you are compiling MXNet model, make sure .params file only contains model weights.

I also tried a tensorflow model [http://download.tensorflow.org/models/official/20181001_resnet/savedmodels/resnet_v1_fp16_savedmodel_NHWC.tar.gz](url)
Compress the .pb file and the variables directory into a .tar.gz file and upload to s3, compile from sagemaker console, failed with the following error:

> Unexpected error during compilation

**Comment by haojin2** [comment]
Hello,
I just used your code to export the resnet50_v1 model from GluonCV and managed to get a successful compilation job on my side. Note that you're using `layout='HWC'` when you're exporting the model, so you should specify the input configuration to be `{'data': (1, 224, 224, 3)}`, and you should do the same for the TF model if it's in NHWC format.
Please let me know if you ever encounter any more problems with compiling models. Thanks!
Hao

**Comment by fast4break** [comment]
@haojin2 Thanks, problem solved and models run on pi.

**Comment by wweic** [comment]
thanks @haojin2 @fast4break .
