### ISSUE TITLE
Building on Mac OS X

### ISSUE THREAD

**Issue by saranyailla** [neo-ai/neo-ai-dlr#261]
Hello,
I am following the steps mentioned at: https://neo-ai-dlr.readthedocs.io/en/latest/install.html#building-on-mac-os-x to build `dlr` on my mac.  I am trying to install the version 1.3.0 of dlr. However, building on the latest branch is also failing with the same error. 

`make -j4` command fails with the following output 
```
[ 25%] Linking CXX shared library libgtest.dylib
ld: unknown option: --exclude-libs
collect2: error: ld returned 1 exit status
make[2]: *** [googletest/googletest-build/googlemock/gtest/libgtest.dylib] Error 1
make[1]: *** [googletest/googletest-build/googlemock/gtest/CMakeFiles/gtest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
......
[ 75%] Linking CXX static library libtvm_runtime_static.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libtvm_runtime_static.a(rpc_pipe_impl.cc.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libtvm_runtime_static.a(rpc_pipe_impl.cc.o) has no symbols
[ 75%] Built target tvm_runtime_static
```

The behavior is same with any `gcc` version over 8. The `cmake` version that I am using is `3.18.4`

Upon explicitly setting `export CMAKE_SYSTEM_NAME=darwin`, the build continues to 81% and errors out with the same  error. 

```
ld: unknown option: --exclude-libs
collect2: error: ld returned 1 exit status
make[2]: *** [googletest/googletest-build/googlemock/gtest/libgtest.dylib] Error 1
make[1]: *** [googletest/googletest-build/googlemock/gtest/CMakeFiles/gtest.dir/all] Error 2 
```

**Comment by trevor-m** [comment]
Thanks @saranyailla for reporting this issue. It looks like `--exclude-libs` ld option is not supported by Mac. We will need to change the build rules to not include that option for Mac.

**Comment by saranyailla** [comment]
Thanks for your help, after changing the line 74 in CMakeLists.txt to `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wl,-t")` on mac, I am able to build with no problem. May I know when you intend to fix this as we our application directly pulls the repo from github and build it.
