### ISSUE TITLE
Cant install on Windows  error: can't copy '..\build\lib\libdlr.so': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by zubairahmed-ai** [neo-ai/neo-ai-dlr#3]
I ran the following command after `python setup.py build` ran successfully

> `python setup.py install`

I get the following error

D:\ProgramData\Anaconda3\envs\tfod\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'root_script_source_version'
  warnings.warn(msg)
D:\ProgramData\Anaconda3\envs\tfod\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'default_python'
  warnings.warn(msg)
D:\ProgramData\Anaconda3\envs\tfod\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'test_command'
  warnings.warn(msg)
D:\ProgramData\Anaconda3\envs\tfod\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'doc_command'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
writing dlr.egg-info\PKG-INFO
writing dependency_links to dlr.egg-info\dependency_links.txt
writing requirements to dlr.egg-info\requires.txt
writing top-level names to dlr.egg-info\top_level.txt
reading manifest file 'dlr.egg-info\SOURCES.txt'
writing manifest file 'dlr.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
installing package data to build\bdist.win-amd64\egg
running install_data
`error: can't copy '..\build\lib\libdlr.so': doesn't exist or not a regular file`

**Comment by wweic** [comment]
Hi @zubairahmed-ai thanks for reporting the issue. https://github.com/neo-ai/neo-ai-dlr/commit/62178d47b6d2a62e318ec037b7a9b60b933f9243 was added to fix the copy issue, I'll close this issue. Though seems like you still have issues in https://github.com/neo-ai/neo-ai-dlr/issues/10, let's work form there.

**Comment by zubairahmed-ai** [comment]
Thanks, I'll get this and try again
I still got the CMAKE issue though you like said, so please let me know

**Comment by zubairahmed-ai** [comment]
> @zubairahmed-ai Yes, there are still problems we need to solve. Let's use #10 for tracking resolution. Thanks!

Ok lets do that.
