### ISSUE TITLE
Cannot download 1.6.0 whl from release page

### ISSUE THREAD

**Issue by alexgorb2016** [neo-ai/neo-ai-dlr#305]
Hi, I cannot download from this link - https://neo-ai-dlr-release.s3-us-west-2.amazonaws.com/v1.6.0/rasp4b/dlr-1.6.0-py3-none-any.whl
Got 
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>40F15F0CB61BE99F</RequestId>
<HostId>CQwijqzrOpSVkI3NE+170TNUu2TaAydds5CGVcMzqJ5rUIl6fqsB0hWWOBGwBjra2+vogRxEyAM=</HostId>
</Error>

Could you please fix it?

**Comment by TusharKanekiDey** [comment]
Hi @alexgorb2016. Thanks for pointing this issue.
The issue has been now resolved and the object for all dlr can be downloaded publicly.
