### ISSUE TITLE
Failure in running TensorRT while running inference on different models 

### ISSUE THREAD

**Issue by nwils** [neo-ai/neo-ai-dlr#318]
Hi,

I am trying to run two different SageMaker Neo compiled models on Jetson Nano. 
DLR version - 1.3
Jetpack -4.3

The models were compiled for ARM64 platform with the following parameters. 
Compilation configuration - 
Arch - ARM64
OS = LINUX
Accelerator = Nvidia
Compiler options = {"cuda-ver": "10.0", "trt-ver": "6.0.1", "gpu-code": "sm_53"}

The libdlr.so module in the model artifact was used to run inference. Loading a model followed by the other causes error as follows.

`dlr.dlr_model.DLRError: TVMError: 
An internal invariant was violated during the execution of TVM.
Please read TVM's error reporting guidelines.
More details can be found here: https://discuss.tvm.ai/t/error-reporting/7793.
  Check failed: context->execute(batch_size_, bindings.data()) == false: Running TensorRT failed.
Stack trace:
  File "/home/nvidia/neo-ai-dlr/3rdparty/tvm/src/runtime/contrib/tensorrt/tensorrt_runtime.cc", line 154
  [bt] (0) /app/model_cache/libdlr.so(+0x201134) [0x7f3342f134]
  [bt] (1) /app/model_cache/libdlr.so(tvm::runtime::contrib::TensorRTRuntime::Run()+0xb40) [0x7f33440558]
  [bt] (2) /app/model_cache/libdlr.so(std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::runtime::json::JSONRuntimeBase::GetFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#3}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&)+0xdc) [0x7f33436afc]
  [bt] (3) /app/model_cache/libdlr.so(+0x27d7b4) [0x7f334ab7b4]
  [bt] (4) /app/model_cache/libdlr.so(+0x27d83c) [0x7f334ab83c]
  [bt] (5) /app/model_cache/libdlr.so(dlr::TVMModel::Run()+0xc4) [0x7f333208b4]
  [bt] (6) /app/model_cache/libdlr.so(RunDLRModel+0x1c) [0x7f332d712c]
[File : run.py, Function : main, Line : 161] ERROR: failed to load model
Traceback (most recent call last):
  File "/app/neo/neo_model.py", line 133, in load_model
    self._model.run(tmp_input_data)
  File "/usr/local/lib/python3.8/site-packages/dlr/api.py", line 135, in run
    raise ex
  File "/usr/local/lib/python3.8/site-packages/dlr/api.py", line 132, in run
    return self._impl.run(input_values)
  File "/usr/local/lib/python3.8/site-packages/dlr/dlr_model.py", line 470, in run
    self._run()
  File "/usr/local/lib/python3.8/site-packages/dlr/dlr_model.py", line 351, in _run
    self._check_call(self._lib.RunDLRModel(byref(self.handle)))
  File "/usr/local/lib/python3.8/site-packages/dlr/dlr_model.py", line 185, in _check_call
    raise DLRError(self._lib.DLRGetLastError().decode('ascii'))`

The tensorrt cache is same for both models. It has been noted that a new tensorrt plan is not created for the next model.
Is it possible to generate different tensorrt plans for different models? Or is there any other solution for this?
Can you please help us to solve this problem?

Thanks in advance.

**Comment by mycpuorg** [comment]
I noticed that you use DLR 1.3 version which is pretty old, could you please use the latest version?
You could compile your model with AWS SageMaker Neo again and get the latest DLR library with the compiled artifact.

**Comment by nwils** [comment]
Thank you very much for your reply. I tried to run the new compiled models with neo-dlr 1.7 version. The problem still exists.

**Comment by trevor-m** [comment]
Hi @nwils you mentioned you are using the [TVM_TENSORRT_CACHE_DIR](https://neo-ai-dlr.readthedocs.io/en/latest/tensorrt.html#caching-tensorrt-engines) flag? Are you able to use both models on their own separately (with or without caching)?

With a recent update, the cache directory is now specific to a single model only. If you are loading two models, you will now need to change the cache directory between. I will make a note to update the documentation.

```
# Load first model
os.environ["TVM_TENSORRT_CACHE_DIR"] = "model1_dir/"
model1 = dlr.DLRModel(...)
# Run inference at least one to load cached engine
model1.run()

# Load second model
os.environ["TVM_TENSORRT_CACHE_DIR"] = "model2_dir/"
model2 = dlr.DLRModel(...)
# Run inference at least one to load cached engine
model2.run()
```

**Comment by nwils** [comment]
Hi,
The models work fine with separate tensorrt caches. Thank you very much.
