### ISSUE TITLE
dlr 1.7.0 pip wheel for x86_64 target

### ISSUE THREAD

**Issue by saranyailla** [neo-ai/neo-ai-dlr#319]
The latest version of `dlr` using pip wheel for x86_64 targets is `1.6.0` where as the rest of the platforms have 1.7.0 pip wheel. Can you let us know when that will be out?

**Comment by TusharKanekiDey** [comment]
Thanks @saranyailla for bringing it to our notice.
We have updated the pip wheels- 
https://pypi.org/project/dlr/1.7.0/
https://pypi.org/project/dlr/1.8.0/
