### ISSUE TITLE
Loading DLR models compiled with Sagemaker Neo

### ISSUE THREAD

**Issue by brightsparc** [neo-ai/neo-ai-dlr#34]
Hi, 

I've built the neo runtime in a centos Docker container based on [ci_build](https://github.com/neo-ai/neo-ai-dlr/blob/master/tests/ci_build/Dockerfile.cpu_bare).

I am getting an error when performing inference on my [custom model](https://s3.amazonaws.com/sagemaker-us-east-1-423079281568/virtual-concierge/model-ml_m4.tar.gz) which I compiled with SageMaker Neo targeting the `ml_m4` instance family:

```
  File "/root/.local/lib/python2.7/site-packages/dlr-1.0-py2.7.egg/dlr/api.py", line 115, in __init__
    c_int(dev_id)))
  File "/root/.local/lib/python2.7/site-packages/dlr-1.0-py2.7.egg/dlr/api.py", line 72, in _check_call
    raise DLRError(_LIB.DLRGetLastError().decode('ascii'))
dlr.api.DLRError: [06:11:18] /workspace/3rdparty/tvm/src/runtime/dso_module.cc:93: Check failed: lib_handle_ != nullptr Failed to load dynamic shared library compiled/model.so /lib64/libc.so.6: version `GLIBC_2.14' not found (required by compiled/model.so)
```

I am able to successfully load & run inference on the test models in this project.  Is there a different instance family I should target, or another way for me to compile my mxnet model such that it can be loaded by the DLR?

Thanks,
Julian.

**Comment by hcho3** [comment]
I think the machine that is running DLR doesn't have correct GLIBC version. What OS is it?

**Comment by ziyu-guo** [comment]
Hi @brightsparc, Neo-compiled model artifacts will ask for GLIBC 2.14, while centos 6 have 2.12. 

Solution would be either to build and compile with upstream TVM (ml_m4 uses tvm target "llvm -mcpu=core-avx2") in the current centos6 docker container, or building DLR in a newer docker container with GLIBC 2.14.

**Comment by brightsparc** [comment]
Thanks I resolved this by building on latest Amazon Linux.
