### ISSUE TITLE
[RFC] Support alternative runtimes

### ISSUE THREAD

**Issue by apivovarov** [neo-ai/neo-ai-dlr#46]
I'd like to discuss how DLR can support alternative runtimes. e.g. Tensorflow, Tensorflow Lite, etc.

Currently we have `DLRModel` class which accepts `model_path` and `device` parameters. 
We can use model files format to determine what runtime should be used. E.g. if model is represented by `.pb` file then it indicates that DLR needs to use `tensorflow` runtime.

In order to support for Tensorflow runtime and at the same time preserve current API we can do the following refactoring:
- add IDLRModel abstract class with `@abc.abstractmethod run(self, input_data)` and other "public" method
- move all DLRModel implementation to DLRModelImpl class
- make DLRModelImpl to be sub-class of IDLRModel
- add `TFModelImpl(IDLRModel)` class which incapsulates details on how to run tensorflow models.
- make DLRModel to be a wrapper on top of particular implementation. __init__ method will decide which impl to create based on format of the model files.

The diagram and the code below illustrate the idea
### Diagram
![DLRModel](https://user-images.githubusercontent.com/218087/56775105-6930fd00-677a-11e9-82fe-913ea0903af8.png)

### Code Example
```
import abc

# Interface
class IDLRModel:
    __metaclass__=abc.ABCMeta

    @abc.abstractmethod
    def get_input_names(self):
        return


    @abc.abstractmethod
    def get_input(self, name, shape=None):
        return


    @abc.abstractmethod
    def run(self, input_data):
        return

# Wrapper class
class DLRModel(IDLRModel):
    def __init__(self, model_path, device):
        if model_path.endswith(".pb"):
            self._impl = TFModelImpl(model_path, device)
        else:
            self._impl = DLRModelImpl(model_path, device) 


    def run(self, input_data):
        return self._impl.run(input_data)


# Current DLRModel code will be moved to  DLRModelImpl
class DLRModelImpl(IDLRModel):
    def __init__(self, model_path, device):
        self.model_path = model_path
        self.device = device


    def run(self, input_data):
        return "TVM/Treelite model run {}".format(input_data)


# New class which support .pb models execution on tensorflow runtime
class TFModelImpl(IDLRModel):
    def __init__(self, model_path, device):
        self.model_path = model_path
        self.device = device


    def run(self, input_data):
        # import tensorflow as tf
        # res = sess.run(output_tensors, feed_dict={input_tensor: np_input})
        # return res
        return "TF model run {}".format(input_data)
```
Test run
```
# Test original DLR models
d = DLRModel("mymodel", "cpu")
print(type(d))
print(d.run("test"))

# Test TF models
d = DLRModel("mymodel.pb", "cpu")
print(type(d))
print(d.run("test"))

<class '__main__.DLRModel'>
TVM/Treelite model run test
<class '__main__.DLRModel'>
TF model run test
```

**Comment by yongwww** [comment]
cc: @zhiics @hcho3  @wweic @kevinthesun

**Comment by zhiics** [comment]
@apivovarov Thanks to bring this up. I agree that it is a much cleaner design to have a pure abstract class and implement each runtime using a separate class. If you want, probably you can also refactor the C++ backend as well so that we can easily extend it to support other runtimes (probably in a few PRs).

**Comment by ziyu-guo** [comment]
#54 implements this design. We probably want to add the TF test models to our s3 bucket as well.

**Comment by apivovarov** [comment]
We already added Tensorflow, TFLite and even custom Hexagon runtimes. I guess RFC can be closed
